FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
RUN pip install --user django-crispy-forms
RUN pip install Pillow
CMD python manage.py migrate \
  && python manage.py runserver 0:8000
