# Generated by Django 3.0.4 on 2020-03-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
    ]
