# Generated by Django 3.2.7 on 2021-11-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='game_default.png', upload_to='game_pics'),
        ),
    ]
