# Generated by Django 3.2.8 on 2021-11-24 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elo_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.game'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='score_A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_B',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.company')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='participant_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_A', to='stats.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='participant_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_B', to='stats.player'),
        ),
    ]
