# Generated by Django 3.2.8 on 2021-11-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20211124_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='elo_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_A',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_B',
            field=models.IntegerField(null=True),
        ),
    ]
