# Generated by Django 3.2.8 on 2021-11-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20211126_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
