# Generated by Django 3.2.8 on 2021-11-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
