# Generated by Django 3.2.7 on 2021-11-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_match_match_date'),
        ('stats', '0013_remove_company_slug'),
    ]

    operations = [
    ]
