# Generated by Django 3.2.8 on 2021-12-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_upcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
