# Generated by Django 3.2.7 on 2021-12-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_elorating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elorating',
            old_name='rating',
            new_name='mu',
        ),
        migrations.AddField(
            model_name='elorating',
            name='sigma',
            field=models.FloatField(null=True),
        ),
    ]
