# Generated by Django 3.2.7 on 2021-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_auto_20211208_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='elo_change',
            new_name='elo_A',
        ),
        migrations.AddField(
            model_name='match',
            name='elo_B',
            field=models.IntegerField(null=True),
        ),
    ]
