# Generated by Django 3.2.8 on 2021-12-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_auto_20211208_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invite_code',
            field=models.CharField(default='defaultInviteCode', max_length=32),
        ),
    ]
