# Generated by Django 3.2.8 on 2021-12-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_company_invite_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
