# Generated by Django 3.2.9 on 2021-12-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
