# Generated by Django 3.2.8 on 2021-12-13 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0024_delete_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admins',
        ),
        migrations.AddField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
