# Generated by Django 3.2.9 on 2021-12-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_alter_game_slug'),
        ('stats', '0026_alter_company_admins'),
    ]

    operations = [
    ]
